# Euler - problem 45
"""Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle            Tn=n(n+1)/2             1, 3, 6, 10, 15,...
Pentagonal        Pn = n(3n - 1)/2        1, 5, 12, 22, 35,...
Hexagonal        Hn = n(2n - 1)           1, 6, 15, 28, 45,...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal."""

def pentagonalnum(n):
    return n*(3*n - 1)/2

def hexagonalnum(n):
    return n*(2*n - 1)

#IDEA: All hexagonal numbers are triangle numbers, so no need to compute triangle numbers
pentagonnums = []
hexagonnums = []
num = 1
nummatches = 0
while nummatches < 2:
    num = num + 1
    pentagonnums.append(pentagonalnum(num))
    hexagonnums.append(hexagonalnum(num))
    if pentagonnums[-1] in hexagonnums:
        nummatches += 1

print pentagonnums[-1]
